
name: Running Shoes Database Tests

on: [push]

jobs:
  Test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres

        env:
          POSTGRES_PASSWORD: 3fmTFYQ4m0F732Do6sC3Da_hxJykVWSQ
          POSTGRES_USER: vrlqybxn
          POSTGRES_DB: vrlqybxn

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
          
    steps:
      # run steps required in the workflow
      - name: Checkout repository
        uses: actions/checkout@v2

  - name: Set up Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          
          - name: Install dependencies
        run: npm install

env:
          URL: "postgres://vrlqybxn:3fmTFYQ4m0F732Do6sC3Da_hxJykVWSQ@silly.db.elephantsql.com/vrlqybxn"
- name: Run the mock tests function
        run: npm test
        env:
          URL: postgres://vrlqybxn:3fmTFYQ4m0F732Do6sC3Da_hxJykVWSQ@silly.db.elephantsql.com/vrlqybxn
